# Generated by Django 5.1.1 on 2024-10-06 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentications", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="type",
            field=models.CharField(
                choices=[
                    ("UNKNOWN", "Unknown"),
                    ("ADMIN", "Admin"),
                    ("CUSTOMER", "Customer"),
                    ("STAFF", "Staff"),
                    ("VENDOR", "Vendor"),
                ],
                max_length=20,
            ),
        ),
    ]
