# Generated by Django 5.1.1 on 2024-10-08 10:54

import authentications.utils
import versatileimagefield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentications", "0002_alter_user_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="image",
            field=versatileimagefield.fields.VersatileImageField(
                blank=True,
                null=True,
                upload_to=authentications.utils.get_user_media_path_prefix,
                verbose_name="Image",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="type",
            field=models.CharField(
                choices=[
                    ("UNKNOWN", "Unknown"),
                    ("ADMIN", "Admin"),
                    ("CUSTOMER", "Customer"),
                    ("STAFF", "Staff"),
                    ("VENDOR", "Vendor"),
                ],
                default="UNKNOWN",
                max_length=20,
            ),
        ),
    ]
